# Generated by Django 3.0.3 on 2020-07-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20200704_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
