# Generated by Django 3.0.3 on 2020-07-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_loginentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginentry',
            name='session_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
